
from frappe.desk.page.setup_wizard.setup_wizard import make_records


def after_install():
	create_property_setters()
	create_salary_components()

def create_property_setters():
	records = [
        {
            "doc_type": "Salary Component",
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "type",
            "module": "BCN Myanmar Payroll",
            "name": "Salary Component-type-options",
            "property": "options",
            "property_type": "Select",
            "value": "Earning\nDeduction\nContribution"
        },
        {
            "doc_type": "Salary Structure Assignment",
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "module": "BCN Myanmar Payroll",
            "name": "Salary Structure Assignment-main-field_order",
            "property": "field_order",
            "property_type": "Data",
            "value": "[\"employee\", \"employee_name\", \"department\", \"designation\", \"grade\", \"column_break_6\", \"salary_structure\", \"from_date\", \"income_tax_slab\", \"column_break_11\", \"company\", \"payroll_payable_account\", \"currency\", \"section_break_7\", \"base\", \"column_break_9\", \"variable\", \"amended_from\", \"opening_balances_section\", \"taxable_earnings_till_date\", \"column_break_20\", \"tax_deducted_till_date\", \"custom_bcn_exempted_from_income_tax_till_date\", \"custom_section_break_iup4j\", \"custom_bcn_contributed_amount_till_date\", \"section_break_17\", \"payroll_cost_centers\"]"
        },
        {
            "doc_type": "Salary Structure Assignment",
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "module": "BCN Myanmar Payroll",
            "name": "Salary Structure Assignment-section_break_17-description",
            "property": "description",
            "property_type": "Text",
            "value": ""
        }
    ]
	make_records(records)

def create_salary_components():
	records = [
		{
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "condition": "custom_bcn_enable_ssc and custom_bcn_ssc_hscis_category == \"60yrs old and under\"",
            "create_separate_payment_entry_against_benefit_claim": 0,
            "custom_bcn_is_myanmar_ssc": 1,
            "custom_bcn_is_one_time_contribution": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 0,
            "description": "Social Security Contribution 2% by employee",
            "disabled": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 1,
            "formula": "B * 0.02 if B < 300000 else 6000",
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "name": "SSC 2% (EE)",
            "only_tax_impact": 0,
            "pay_against_benefit_claim": 0,
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "SSC 2% (EE)",
            "salary_component_abbr": "SSC_20",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0
        },
		{
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "condition": "custom_bcn_enable_ssc and custom_bcn_ssc_hscis_category == \"60yrs old and under\"",
            "create_separate_payment_entry_against_benefit_claim": 0,
            "custom_bcn_is_myanmar_ssc": 1,
            "custom_bcn_is_one_time_contribution": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 0,
            "description": "Social Security Contribution 2% by employer",
            "disabled": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "formula": "B * 0.02 if B < 300000 else 6000",
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "name": "SSC 2% (ER)",
            "only_tax_impact": 0,
            "pay_against_benefit_claim": 0,
            "remove_if_zero_valued": 0,
            "round_to_the_nearest_integer": 0,
            "salary_component": "SSC 2% (ER)",
            "salary_component_abbr": "SSC_EC_20",
            "statistical_component": 0,
            "type": "Contribution",
            "variable_based_on_taxable_salary": 0
        },
		{
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "condition": "custom_bcn_enable_ssc and custom_bcn_ssc_hscis_category == \"Over 60yrs old\"",
            "create_separate_payment_entry_against_benefit_claim": 0,
            "custom_bcn_is_myanmar_ssc": 1,
            "custom_bcn_is_one_time_contribution": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 0,
            "description": "Social Security Contribution 2.5% by employee",
            "disabled": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 1,
            "formula": "B * 0.025 if B < 300000 else 7500",
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "name": "SSC 2.5% (EE)",
            "only_tax_impact": 0,
            "pay_against_benefit_claim": 0,
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "SSC 2.5% (EE)",
            "salary_component_abbr": "SSC_25",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0
        },
		{
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "condition": "custom_bcn_enable_ssc and custom_bcn_ssc_hscis_category == \"Over 60yrs old\"",
            "create_separate_payment_entry_against_benefit_claim": 0,
            "custom_bcn_is_myanmar_ssc": 1,
            "custom_bcn_is_one_time_contribution": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 0,
            "description": "Social Security Contribution 2.5% by employer",
            "disabled": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "formula": "B * 0.025 if B < 300000 else 7500",
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "name": "SSC 2.5% (ER)",
            "only_tax_impact": 0,
            "pay_against_benefit_claim": 0,
            "remove_if_zero_valued": 0,
            "round_to_the_nearest_integer": 0,
            "salary_component": "SSC 2.5% (ER)",
            "salary_component_abbr": "SSC_EC_25",
            "statistical_component": 0,
            "type": "Contribution",
            "variable_based_on_taxable_salary": 0
        },
		{
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "condition": "custom_bcn_enable_ssc",
            "create_separate_payment_entry_against_benefit_claim": 0,
            "custom_bcn_is_myanmar_ssc": 1,
            "custom_bcn_is_one_time_contribution": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 0,
            "description": "Social Security Contribution 1% by employer",
            "disabled": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "formula": "B * 0.01 if B < 300000 else 3000",
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "name": "SSC 1% (ER)",
            "only_tax_impact": 0,
            "pay_against_benefit_claim": 0,
            "remove_if_zero_valued": 0,
            "round_to_the_nearest_integer": 0,
            "salary_component": "SSC 1% (ER)",
            "salary_component_abbr": "SSC_EC_10",
            "statistical_component": 0,
            "type": "Contribution",
            "variable_based_on_taxable_salary": 0
        }
	]

	make_records(records)
